/**
 * Shared aspect-ratio support for every image tool (F3): 1:1, 4:5, 9:16, 16:9.
 *
 * Providers that lack a ratio (Grok Imagine has no 4:5) generate the nearest native ratio and
 * the result is reframed deterministically (cover-crop by default, or extend with mirrored
 * edges). Backgrounds / plates are safe to crop; callers that need the exact requested ratio
 * use `reframeToRatio` on the generated bytes.
 */
import sharp, { type Sharp } from 'sharp'
import { GROK_NATIVE_ASPECT_RATIOS } from './grok-image-edit.js'

export const SUPPORTED_IMAGE_RATIOS = ['1:1', '4:5', '9:16', '16:9'] as const
export type SupportedImageRatio = (typeof SUPPORTED_IMAGE_RATIOS)[number]

/** Canonical output size per supported ratio (social-ready). */
export const RATIO_OUTPUT_SIZE: Record<SupportedImageRatio, { width: number; height: number }> = {
  '1:1': { width: 1080, height: 1080 },
  '4:5': { width: 1080, height: 1350 },
  '9:16': { width: 1080, height: 1920 },
  '16:9': { width: 1920, height: 1080 },
}

export function ratioValue(ratio: string): number | null {
  const m = String(ratio ?? '').trim().match(/^(\d+(?:\.\d+)?):(\d+(?:\.\d+)?)$/)
  if (!m) return null
  const w = Number(m[1])
  const h = Number(m[2])
  return w > 0 && h > 0 ? w / h : null
}

export function isSupportedImageRatio(ratio: unknown): ratio is SupportedImageRatio {
  return typeof ratio === 'string' && (SUPPORTED_IMAGE_RATIOS as readonly string[]).includes(ratio.trim())
}

/** Grok-native ratios (without 'auto'). */
export const GROK_NATIVE_RATIOS: readonly string[] = GROK_NATIVE_ASPECT_RATIOS.filter((r) => r !== 'auto')

/**
 * Nearest native ratio for a requested one (log distance). Exact natives map to themselves.
 * `needsReframe` is true when the generated image must be reframed to the requested ratio.
 */
export function nativeRatioFor(requested: string, native: readonly string[] = GROK_NATIVE_RATIOS): { native: string; needsReframe: boolean } {
  const raw = String(requested ?? '').trim() || '9:16'
  if (native.includes(raw)) return { native: raw, needsReframe: false }
  const v = ratioValue(raw)
  if (v === null) throw new Error(`Unsupported aspectRatio "${raw}". Supported: ${SUPPORTED_IMAGE_RATIOS.join(', ')}.`)
  let best = native[0]
  let bestD = Infinity
  for (const r of native) {
    const rv = ratioValue(r)
    if (rv === null) continue
    const d = Math.abs(Math.log(v / rv))
    if (d < bestD) {
      bestD = d
      best = r
    }
  }
  return { native: best, needsReframe: true }
}

/**
 * Validate a ratio for an image tool: any supported ratio or any provider-native ratio is accepted.
 * Returns the ratio to request from the provider and whether to reframe afterwards.
 */
export function resolveImageRatio(requested: unknown, fallback: SupportedImageRatio = '9:16'): { requested: string; generateAt: string; needsReframe: boolean } {
  const raw = typeof requested === 'string' && requested.trim() ? requested.trim() : fallback
  if (!isSupportedImageRatio(raw) && !GROK_NATIVE_RATIOS.includes(raw)) {
    throw new Error(`Unsupported aspectRatio "${raw}". Supported: ${SUPPORTED_IMAGE_RATIOS.join(', ')} (and Grok-native ${GROK_NATIVE_RATIOS.join(', ')}).`)
  }
  const { native, needsReframe } = nativeRatioFor(raw)
  return { requested: raw, generateAt: native, needsReframe }
}

export interface ReframeOptions {
  /** cover = center crop (default); extend = pad with mirrored, blurred edges (nothing is cut). */
  mode?: 'cover' | 'extend'
  /** Output long side cap (keeps the source resolution otherwise). */
  maxLongSide?: number
  format?: 'png' | 'jpeg'
}

/** Deterministically reframe image bytes to an exact ratio. */
export async function reframeToRatio(bytes: Uint8Array, ratio: string, opts: ReframeOptions = {}): Promise<{ bytes: Buffer; width: number; height: number; mimeType: string }> {
  const v = ratioValue(ratio)
  if (v === null) throw new Error(`invalid ratio ${ratio}`)
  const meta = await sharp(bytes).metadata()
  const sw = meta.width ?? 0
  const sh = meta.height ?? 0
  if (!sw || !sh) throw new Error('reframe: unreadable image')
  const format = opts.format ?? 'png'
  const encode = (img: Sharp) => (format === 'jpeg' ? img.jpeg({ quality: 92 }) : img.png())
  const cur = sw / sh
  let out: Buffer
  let width: number
  let height: number
  if (Math.abs(cur - v) / v < 0.002) {
    out = await encode(sharp(bytes).rotate()).toBuffer()
    width = sw
    height = sh
  } else if ((opts.mode ?? 'cover') === 'cover') {
    // Largest centered crop with the target ratio.
    width = cur > v ? Math.round(sh * v) : sw
    height = cur > v ? sh : Math.round(sw / v)
    out = await encode(sharp(bytes).rotate().extract({ left: Math.floor((sw - width) / 2), top: Math.floor((sh - height) / 2), width, height })).toBuffer()
  } else {
    width = cur > v ? sw : Math.round(sh * v)
    height = cur > v ? Math.round(sw / v) : sh
    const padX = width - sw
    const padY = height - sh
    const extended = await sharp(bytes)
      .rotate()
      .extend({ left: Math.floor(padX / 2), right: Math.ceil(padX / 2), top: Math.floor(padY / 2), bottom: Math.ceil(padY / 2), extendWith: 'mirror' })
      .toBuffer()
    // Soften the mirrored band so it reads as background, then put the original pixels back on top.
    const blurred = await sharp(extended).blur(18).toBuffer()
    out = await encode(sharp(blurred).composite([{ input: await sharp(bytes).rotate().toBuffer(), left: Math.floor(padX / 2), top: Math.floor(padY / 2) }])).toBuffer()
  }
  if (opts.maxLongSide && Math.max(width, height) > opts.maxLongSide) {
    const k = opts.maxLongSide / Math.max(width, height)
    width = Math.round(width * k)
    height = Math.round(height * k)
    out = await encode(sharp(out).resize(width, height, { fit: 'fill' })).toBuffer()
  }
  return { bytes: out, width, height, mimeType: format === 'jpeg' ? 'image/jpeg' : 'image/png' }
}
