export type ChatShellLanguage = 'en' | 'es'

export const chatShellLabels = {
  es: {
    chat: 'Chat',
    context: 'Contexto',
    offers: 'Ofertas',
    images: 'Imágenes',
    brand: 'Marca',
    more: 'Más',
    create: 'Crear',
    createHint: 'Misma generación que el workspace anterior: configurá y generá. El chat sigue disponible.',
    generatePost: 'Generar post',
    closeRail: 'Cerrar panel',
    openRail: 'Abrir panel',
    workspace: 'Espacio',
    options: 'Opciones',
    backToWidget: 'Volver',
    openNav: 'Abrir navegación',
    closeNav: 'Cerrar navegación',
    noBrand: 'Sin marca',
    noSession: 'Sin sesión',
    noOffer: 'Sin oferta',
    newChat: 'Chat nuevo',
    newBrand: 'Nueva marca',
    settings: 'Configuración',
    openTour: 'Cómo funciona',
    admin: 'Admin',
    scripts: 'Guiones',
    posts: 'Posts',
    descriptions: 'Descripciones',
    replies: 'Respuestas',
    askScripts: 'Pedí guiones…',
    askPost: 'Elegí tipo o tamaño del post…',
    askScriptType: 'Elegí el tipo de guion…',
    chooseOffers: 'Elegí ofertas en el panel, luego pedí un guión…',
    selectSession: 'Elegí una sesión para escribir',
    send: 'Enviar',
    you: 'Tú',
    generating: 'Generando',
    composer: 'Escribir mensaje',
    voice: 'Dictar mensaje',
    voiceStop: 'Detener grabación',
    voiceListening: 'Escuchando…',
    voiceTranscribing: 'Pasando a texto…',
    voiceUnsupported: 'El micrófono no está disponible en este navegador',
    attach: 'Adjuntar',
    attachLogo: 'Logo',
    attachReference: 'Referencia visual',
    attachDocument: 'Documento o PDF',
    paletteSaved: 'Paleta guardada. La uso en las imágenes.',
    logoSaved: 'Logo guardado. Lo uso en los posts.',
    referenceSaved: 'Referencia guardada. La uso como guía visual en las imágenes.',
    attachSoon: 'Adjuntos próximamente',
    previewFooter: 'Plan',
    resumeSetup: 'Reanudar setup',
    improveSetup: 'Mejorar setup de la marca',
    retryFailed: 'Reintentar ofertas fallidas',
    failedOffers: 'Ofertas fallidas',
    loadingChat: 'Cargando chat…',
    loadingSession: 'Cargando sesión…',
    emptyThread: 'Escribí para generar guiones o imágenes.',
    bestModel: 'Mejor calidad',
    efficientModel: 'Más rápido',
    logo: 'Logo',
    productPhoto: 'Foto de producto',
    usage: 'Uso',
    openOffers: 'Abrir ofertas',
    linkedOffer: 'Esta oferta tiene piezas generadas. No se puede quitar.',
    brands: 'Marcas',
    loadingBrands: 'Cargando marcas…',
    noBrands: 'Sin marcas aún',
    noBrandsDetail: 'Creá tu primera marca para empezar a chatear.',
    newBrandCta: 'Nueva marca',
    noChats: 'Sin chats aún',
    noChatsDetail: 'Empezá un chat para esta marca.',
    loadingSessions: 'Actualizando sesiones…',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    deleteFolder: 'Eliminar carpeta',
    confirmDeleteFolder: 'Eliminar carpeta, chats y ofertas',
    requestEdit: 'Pedir edición',
    downloadImage: 'Descargar',
    optimizeForPost: 'Optimizar para post',
    viewImage: 'Ver imagen',
    addReference: 'Agregar referencia',
    imagesHint: 'Galería de esta oferta. Generá posts desde Crear o el chat. Pedí una edición para abrir un chat nuevo.',
    noImagesYet: 'Todavía no hay imágenes para esta oferta.',
    editReason: '¿Qué debería cambiar?',
    editSessionSeed: 'Decime el cambio y lo aplico sobre esta imagen.',
    previewEnv: 'Preview',
    scriptsUsed: 'Guiones',
    imagesUsed: 'Imágenes',
    creditsRemaining: 'Créditos IA',
    quickGenerate: 'Generar rápido',
    showLess: 'Ver menos',
    newSession: 'Nueva sesión',
    useClassic: 'Volver al panel clásico',
    classicShort: 'Clásico',
    assignToBrand: 'Asignar a esta marca',
    unassignedOffers: 'Productos sin marca',
    openClassicHistory: 'Ver historial clásico',
    deleteUnassigned: 'Eliminar producto sin marca',
    clearUnassigned: 'Eliminar todos los sin marca',
    confirmClearUnassigned: '¿Borrar todos los productos sin marca? Esta acción no se puede deshacer.',
    createOfferTitle: 'Nueva oferta',
    createOfferHint: 'Creá un producto u oferta para esta marca y lo adjuntamos a este chat.',
    offerNameLabel: 'Nombre de la oferta',
    offerNamePlaceholder: 'Ej. Plan Pro, Café de especialidad…',
    offerTypeLabel: 'Tipo',
    offerNameRequired: 'Escribí un nombre para la oferta.',
    createOfferAction: 'Crear y adjuntar',
    creatingOffer: 'Creando…',
    offersPrimary: 'Principal',
    offersAttachHint: 'Elegí hasta {max} productos. La posición 1 es la principal.',
    offersNoneAttached: 'Todavía no hay ofertas adjuntas.',
    offersMaxReached: 'Llegaste al máximo de {max} ofertas.',
    selectSessionOffers: 'Elegí una sesión para adjuntar ofertas.',
    sessionNoBusiness: 'Esta sesión no tiene marca — no se pueden adjuntar ofertas.',
    noBrandProducts: 'Esta marca no tiene productos. Creá uno abajo o asigná uno suelto.',
    showOlder: 'Ver {count} anteriores',
    quickSessionTag: 'Rápido',
    defaultSessionTitle: 'Chat nuevo',
    emptyNoSession: 'Elegí o creá una sesión bajo {brand}.',
    emptyNoBrand: 'Elegí una marca en la barra lateral (o creá una) para empezar.',
    emptyLoading: 'Cargando conversación…',
    emptyReadyWithOffer: 'Sesión lista · {detail}. Pedí un guion o una imagen para generar.',
    emptyReadyNoOffer: 'Sesión lista · todavía no hay oferta. Creá una en el panel Ofertas o confirmá el setup.',
    emptyNeedOfferForScripts: 'Primero necesitás una oferta. Creala en Ofertas o confirmá el setup.',
    emptyFirstRunLine: 'Empezá por tu marca para generar guiones, posts y fotos.',
    emptyFirstRunCta: 'Empezá por tu marca',
    kitBlockedHint: 'Primero el kit',
    openOffersPanel: 'Abrir ofertas',
    showCreateWidget: 'Mostrar Brand Kit',
    hideCreateWidget: 'Ocultar Brand Kit',
    reviewKit: 'Revisar Brand Kit',
    kitReady: 'Brand Kit listo',
    kitTitle: 'Brand Kit',
    kitNotReady: 'Brand Kit incompleto',
    kitNeedsTune: 'Falta afinar',
    createScriptsShort: 'Guiones',
    createPostShort: 'Post',
    createProductShort: 'Foto',
    createBulkShort: 'Pack',
    bulkTitle: 'Pack',
    bulkCopy: 'Ángulos distintos por nicho (no el mismo anuncio con otras palabras). Luego confirmás y generamos.',
    bulkCount: 'Cantidad (2–25)',
    bulkScriptsOnly: 'Solo guiones',
    bulkCampaign: 'Pack campaña',
    bulkStyleDna: 'Style DNA (opcional)',
    bulkStyleDnaNone: 'Sin DNA',
    bulkNeedBoard: 'Proponé el tablero de ángulos antes de confirmar.',
    bulkPropose: 'Proponer ángulos',
    bulkConfirm: 'Confirmar y generar',
    bulkQuote: 'Cotización máxima',
    bulkFailed: 'No se pudo generar el pack',
    flowBack: 'Atrás',
    flowScriptsTitle: 'Guiones',
    flowPostTitle: 'Post',
    flowFotoTitle: 'Foto',
    flowCreditsScript: '{n} créditos · {count} guion(es)',
    flowCreditsImage: '{n} créditos · imagen estándar',
    flowGenerate: 'Generar',
    flowContinue: 'Continuar',
    flowPickType: '¿Qué tipo de guiones querés crear?',
    flowPickCount: '¿Cuántas versiones necesitás?',
    flowPickCta: '¿A dónde debe llevar el CTA?',
    flowPickScript: 'Elegí el guion que querés convertir en post.',
    flowPickMode: '¿Anuncio, producto u orgánico?',
    flowPickAspect: '¿Qué tamaño? Reel, cuadrado o vertical.',
    flowPickDensity: '¿Cuánto texto en el post?',
    flowPickStyle: 'Elegí un estilo.',
    flowPickRefs: 'Confirmá referencias de producto, contexto y logo.',
    brandModalTitle: 'Nueva marca',
    brandModalCopy: 'Creá una marca y pegá la URL de tu tienda para arrancar el setup (o solo el nombre y lo completás en el chat).',
    brandModalName: 'Nombre de la marca',
    brandModalPlaceholder: 'Ej. Acme Studio',
    brandModalUrl: 'URL de la tienda (opcional)',
    brandModalUrlPlaceholder: 'Pegá la URL de tu tienda',
    brandModalUrlHint: 'Si la pegás acá, analizamos el sitio en cuanto se cree el chat.',
    brandModalCancel: 'Cancelar',
    brandModalCreate: 'Crear marca',
    brandModalCreating: 'Creando…',
    classicConfirm: '¿Volver al panel clásico? Podés regresar a Chat desde Configuración.',
    newBrandModalClose: 'Cerrar crear marca',
    sessionActionsFor: 'Acciones de la sesión',
    collapseBrand: 'Cerrar',
    expandBrand: 'Abrir',
    chatsCount: 'chats',
    navLabel: 'Navegación del chat',
    moveImageUp: 'Subir',
    moveImageDown: 'Bajar',
    removeImageRef: 'Quitar',
    imageOfferTablist: 'Oferta de imagen',
  },
  en: {
    chat: 'Chat',
    context: 'Context',
    offers: 'Offers',
    images: 'Images',
    brand: 'Brand',
    more: 'More',
    create: 'Create',
    createHint: 'Same generation as the previous workspace: configure and generate. Chat still works.',
    generatePost: 'Generate post',
    closeRail: 'Close panel',
    openRail: 'Open panel',
    workspace: 'Workspace',
    options: 'Options',
    backToWidget: 'Back',
    openNav: 'Open navigation',
    closeNav: 'Close navigation',
    noBrand: 'No brand',
    noSession: 'No session',
    noOffer: 'No offer',
    newChat: 'New chat',
    newBrand: 'New brand',
    settings: 'Settings',
    openTour: 'How it works',
    admin: 'Admin',
    scripts: 'Scripts',
    posts: 'Posts',
    descriptions: 'Descriptions',
    replies: 'Replies',
    askScripts: 'Ask for scripts…',
    askPost: 'Pick the post type or size…',
    askScriptType: 'Pick a script type…',
    chooseOffers: 'Choose offers in the rail, then ask for a script…',
    selectSession: 'Select a session to compose',
    send: 'Send',
    you: 'You',
    generating: 'Generating',
    composer: 'Message composer',
    voice: 'Dictate message',
    voiceStop: 'Stop recording',
    voiceListening: 'Listening…',
    voiceTranscribing: 'Transcribing…',
    voiceUnsupported: 'Microphone is not available in this browser',
    attach: 'Attach',
    attachLogo: 'Logo',
    attachReference: 'Visual reference',
    attachDocument: 'Document or PDF',
    paletteSaved: 'Palette saved. I’ll use it on images.',
    logoSaved: 'Logo saved. I’ll use it on posts.',
    referenceSaved: 'Reference saved. I’ll use it as visual guidance on images.',
    attachSoon: 'Attachments coming soon',
    previewFooter: 'Plan',
    resumeSetup: 'Resume setup',
    improveSetup: 'Improve folder setup',
    retryFailed: 'Retry failed offers',
    failedOffers: 'Failed offers',
    loadingChat: 'Loading chat…',
    loadingSession: 'Loading session…',
    emptyThread: 'Ask for scripts or images to get started.',
    bestModel: 'Best quality',
    efficientModel: 'Faster',
    logo: 'Logo',
    productPhoto: 'Product photo',
    usage: 'Usage',
    openOffers: 'Open offers',
    linkedOffer: 'This offer has generated artifacts. It cannot be removed.',
    brands: 'Brands',
    loadingBrands: 'Loading brands…',
    noBrands: 'No brands yet',
    noBrandsDetail: 'Create your first brand to start chatting.',
    newBrandCta: 'New brand',
    noChats: 'No chats yet',
    noChatsDetail: 'Start a chat for this brand.',
    loadingSessions: 'Updating sessions…',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteFolder: 'Delete folder',
    confirmDeleteFolder: 'Delete folder, chats, and offers',
    requestEdit: 'Request edit',
    downloadImage: 'Download',
    optimizeForPost: 'Optimize for post',
    viewImage: 'View image',
    addReference: 'Add reference',
    imagesHint: 'Gallery for this offer. Generate posts from Create or chat. Request an edit to open a new chat.',
    noImagesYet: 'No images for this offer yet.',
    editReason: 'What should change?',
    editSessionSeed: 'Tell me the change and I’ll apply it to this image.',
    previewEnv: 'Preview',
    scriptsUsed: 'Scripts',
    imagesUsed: 'Images',
    creditsRemaining: 'AI credits',
    quickGenerate: 'Quick generate',
    showLess: 'Show less',
    newSession: 'New session',
    useClassic: 'Return to classic dashboard',
    classicShort: 'Classic',
    assignToBrand: 'Assign to this brand',
    unassignedOffers: 'Unassigned products',
    openClassicHistory: 'Open classic history',
    deleteUnassigned: 'Delete unassigned product',
    clearUnassigned: 'Remove all unassigned',
    confirmClearUnassigned: 'Delete all unassigned products? This cannot be undone.',
    createOfferTitle: 'New offer',
    createOfferHint: 'Create a product or offer for this brand and attach it to this chat.',
    offerNameLabel: 'Offer name',
    offerNamePlaceholder: 'e.g. Pro Plan, Specialty coffee…',
    offerTypeLabel: 'Type',
    offerNameRequired: 'Enter a name for the offer.',
    createOfferAction: 'Create and attach',
    creatingOffer: 'Creating…',
    offersPrimary: 'Primary',
    offersAttachHint: 'Select up to {max} products. Position 1 is primary.',
    offersNoneAttached: 'No offers attached yet.',
    offersMaxReached: 'Maximum of {max} offers reached.',
    selectSessionOffers: 'Select a session to attach product offers.',
    sessionNoBusiness: 'This session has no brand — cannot attach offers.',
    noBrandProducts: 'This brand has no products yet. Create one below or assign an unassigned product.',
    showOlder: 'Show {count} older',
    quickSessionTag: 'Quick',
    defaultSessionTitle: 'New chat',
    emptyNoSession: 'Select or create a session under {brand}.',
    emptyNoBrand: 'Select a brand in the sidebar (or create one) to get started.',
    emptyLoading: 'Loading conversation…',
    emptyReadyWithOffer: 'Session ready · {detail}. Ask for a script or image to generate.',
    emptyReadyNoOffer: 'Session ready · no offer yet. Create one in Offers or confirm setup.',
    emptyNeedOfferForScripts: 'You need an offer first. Create one in Offers or confirm setup.',
    emptyFirstRunLine: 'Start with your brand to generate scripts, posts, and photos.',
    emptyFirstRunCta: 'Start with your brand',
    kitBlockedHint: 'Kit first',
    openOffersPanel: 'Open offers',
    showCreateWidget: 'Show Brand Kit',
    hideCreateWidget: 'Hide Brand Kit',
    reviewKit: 'Review Brand Kit',
    kitReady: 'Brand Kit ready',
    kitTitle: 'Brand Kit',
    kitNotReady: 'Brand Kit incomplete',
    kitNeedsTune: 'Needs a tune-up',
    createScriptsShort: 'Scripts',
    createPostShort: 'Post',
    createProductShort: 'Photo',
    createBulkShort: 'Pack',
    bulkTitle: 'Pack',
    bulkCopy: 'Distinct buyer-niche angles (not the same ad in different words). Confirm, then we generate.',
    bulkCount: 'Count (2–25)',
    bulkScriptsOnly: 'Scripts only',
    bulkCampaign: 'Campaign pack',
    bulkStyleDna: 'Style DNA (optional)',
    bulkStyleDnaNone: 'No DNA',
    bulkNeedBoard: 'Propose the angle board before confirming.',
    bulkPropose: 'Propose angles',
    bulkConfirm: 'Confirm and generate',
    bulkQuote: 'Maximum quote',
    bulkFailed: 'Could not generate the pack',
    flowBack: 'Back',
    flowScriptsTitle: 'Scripts',
    flowPostTitle: 'Post',
    flowFotoTitle: 'Photo',
    flowCreditsScript: '{n} credits · {count} script(s)',
    flowCreditsImage: '{n} credits · standard image',
    flowGenerate: 'Generate',
    flowContinue: 'Continue',
    flowPickType: 'What kind of scripts do you want?',
    flowPickCount: 'How many versions do you need?',
    flowPickCta: 'Where should the CTA send people?',
    flowPickScript: 'Choose the script you want to turn into a post.',
    flowPickMode: 'Ad, product, or organic?',
    flowPickAspect: 'What size? Reel, square, or vertical.',
    flowPickDensity: 'How much copy on the post?',
    flowPickStyle: 'Pick a style.',
    flowPickRefs: 'Confirm product, context, and logo references.',
    brandModalTitle: 'New brand',
    brandModalCopy: 'Create a brand and paste your store URL to start setup (or just a name and finish in chat).',
    brandModalName: 'Brand name',
    brandModalPlaceholder: 'e.g. Acme Studio',
    brandModalUrl: 'Store URL (optional)',
    brandModalUrlPlaceholder: 'Paste your store URL',
    brandModalUrlHint: 'If you paste it here, we analyze the site as soon as the chat is created.',
    brandModalCancel: 'Cancel',
    brandModalCreate: 'Create brand',
    brandModalCreating: 'Creating…',
    classicConfirm: 'Return to the classic dashboard? You can come back to Chat from Settings.',
    newBrandModalClose: 'Close create brand',
    sessionActionsFor: 'Session actions for',
    collapseBrand: 'Collapse',
    expandBrand: 'Expand',
    chatsCount: 'chats',
    navLabel: 'Chat navigation',
    moveImageUp: 'Move up',
    moveImageDown: 'Move down',
    removeImageRef: 'Remove',
    imageOfferTablist: 'Image offer',
  },
} as const

export function shellT(language: ChatShellLanguage) {
  return chatShellLabels[language] || chatShellLabels.es
}
