export type ChatShellLanguage = 'en' | 'es'

export const chatShellLabels = {
  es: {
    chat: 'Chat',
    context: 'Contexto',
    offers: 'Ofertas',
    images: 'Imágenes',
    brand: 'Marca',
    more: 'Más',
    create: 'Crear',
    createHint: 'Misma generación que el workspace anterior: configurá y generá. El chat sigue disponible.',
    generatePost: 'Generar post',
    closeRail: 'Cerrar panel',
    openRail: 'Abrir panel',
    workspace: 'Espacio',
    options: 'Opciones',
    backToWidget: 'Volver',
    openNav: 'Abrir navegación',
    closeNav: 'Cerrar navegación',
    noBrand: 'Sin marca',
    noSession: 'Sin sesión',
    noOffer: 'Sin oferta',
    newChat: 'Chat nuevo',
    newBrand: 'Nueva marca',
    settings: 'Configuración',
    admin: 'Admin',
    scripts: 'Guiones',
    posts: 'Posts',
    descriptions: 'Descripciones',
    replies: 'Respuestas',
    askScripts: 'Pedí guiones…',
    askPost: 'Elegí tipo o tamaño del post…',
    askScriptType: 'Elegí el tipo de guion…',
    chooseOffers: 'Elegí ofertas en el panel, luego pedí un guión…',
    selectSession: 'Elegí una sesión para escribir',
    send: 'Enviar',
    generating: 'Generando',
    composer: 'Escribir mensaje',
    voice: 'Dictar mensaje',
    voiceStop: 'Detener grabación',
    voiceListening: 'Escuchando…',
    voiceTranscribing: 'Pasando a texto…',
    voiceUnsupported: 'El micrófono no está disponible en este navegador',
    attach: 'Adjuntar',
    attachLogo: 'Logo',
    attachReference: 'Referencia visual',
    attachDocument: 'Documento o PDF',
    paletteSaved: 'Paleta guardada. La uso en las imágenes.',
    logoSaved: 'Logo guardado. Lo uso en los posts.',
    referenceSaved: 'Referencia guardada. La uso como guía visual en las imágenes.',
    attachSoon: 'Adjuntos próximamente',
    previewFooter: 'Plan',
    resumeSetup: 'Reanudar setup',
    improveSetup: 'Mejorar setup de la marca',
    retryFailed: 'Reintentar ofertas fallidas',
    failedOffers: 'Ofertas fallidas',
    loadingChat: 'Cargando chat…',
    loadingSession: 'Cargando sesión…',
    emptyThread: 'Escribí para generar guiones o imágenes.',
    bestModel: 'Grok 4.6 · Mejor',
    efficientModel: 'Grok 4.5 · Eficiente',
    logo: 'Logo',
    productPhoto: 'Foto de producto',
    usage: 'Uso',
    openOffers: 'Abrir ofertas',
    linkedOffer: 'Esta oferta tiene piezas generadas. No se puede quitar.',
    brands: 'Marcas',
    loadingBrands: 'Cargando marcas…',
    noBrands: 'Sin marcas aún',
    noBrandsDetail: 'Creá tu primera marca para empezar a chatear.',
    newBrandCta: 'Nueva marca',
    noChats: 'Sin chats aún',
    noChatsDetail: 'Empezá un chat para esta marca.',
    loadingSessions: 'Actualizando sesiones…',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    deleteFolder: 'Eliminar carpeta',
    confirmDeleteFolder: 'Eliminar carpeta, chats y ofertas',
    requestEdit: 'Pedir edición',
    optimizeForPost: 'Optimizar para post',
    viewImage: 'Ver imagen',
    addReference: 'Agregar referencia',
    imagesHint: 'Galería de esta oferta. Generá posts desde Crear o el chat. Pedí una edición para abrir un chat nuevo.',
    noImagesYet: 'Todavía no hay imágenes para esta oferta.',
    editReason: '¿Qué debería cambiar?',
    editSessionSeed: 'Decime el cambio y lo aplico sobre esta imagen.',
    previewEnv: 'Preview',
    scriptsUsed: 'Guiones',
    imagesUsed: 'Imágenes',
    quickGenerate: 'Generar rápido',
    showLess: 'Ver menos',
    newSession: 'Nueva sesión',
    useClassic: 'Volver al panel clásico',
    classicShort: 'Clásico',
    assignToBrand: 'Asignar a esta marca',
    unassignedOffers: 'Productos sin marca',
    openClassicHistory: 'Ver historial clásico',
    deleteUnassigned: 'Eliminar producto sin marca',
    clearUnassigned: 'Eliminar todos los sin marca',
    confirmClearUnassigned: '¿Borrar todos los productos sin marca? Esta acción no se puede deshacer.',
  },
  en: {
    chat: 'Chat',
    context: 'Context',
    offers: 'Offers',
    images: 'Images',
    brand: 'Brand',
    more: 'More',
    create: 'Create',
    createHint: 'Same generation as the previous workspace: configure and generate. Chat still works.',
    generatePost: 'Generate post',
    closeRail: 'Close panel',
    openRail: 'Open panel',
    workspace: 'Workspace',
    options: 'Options',
    backToWidget: 'Back',
    openNav: 'Open navigation',
    closeNav: 'Close navigation',
    noBrand: 'No brand',
    noSession: 'No session',
    noOffer: 'No offer',
    newChat: 'New chat',
    newBrand: 'New brand',
    settings: 'Settings',
    admin: 'Admin',
    scripts: 'Scripts',
    posts: 'Posts',
    descriptions: 'Descriptions',
    replies: 'Replies',
    askScripts: 'Ask for scripts…',
    askPost: 'Pick the post type or size…',
    askScriptType: 'Pick a script type…',
    chooseOffers: 'Choose offers in the rail, then ask for a script…',
    selectSession: 'Select a session to compose',
    send: 'Send',
    generating: 'Generating',
    composer: 'Message composer',
    voice: 'Dictate message',
    voiceStop: 'Stop recording',
    voiceListening: 'Listening…',
    voiceTranscribing: 'Transcribing…',
    voiceUnsupported: 'Microphone is not available in this browser',
    attach: 'Attach',
    attachLogo: 'Logo',
    attachReference: 'Visual reference',
    attachDocument: 'Document or PDF',
    paletteSaved: 'Palette saved. I’ll use it on images.',
    logoSaved: 'Logo saved. I’ll use it on posts.',
    referenceSaved: 'Reference saved. I’ll use it as visual guidance on images.',
    attachSoon: 'Attachments coming soon',
    previewFooter: 'Plan',
    resumeSetup: 'Resume setup',
    improveSetup: 'Improve folder setup',
    retryFailed: 'Retry failed offers',
    failedOffers: 'Failed offers',
    loadingChat: 'Loading chat…',
    loadingSession: 'Loading session…',
    emptyThread: 'Ask for scripts or images to get started.',
    bestModel: 'Grok 4.6 · Best',
    efficientModel: 'Grok 4.5 · Efficient',
    logo: 'Logo',
    productPhoto: 'Product photo',
    usage: 'Usage',
    openOffers: 'Open offers',
    linkedOffer: 'This offer has generated artifacts. It cannot be removed.',
    brands: 'Brands',
    loadingBrands: 'Loading brands…',
    noBrands: 'No brands yet',
    noBrandsDetail: 'Create your first brand to start chatting.',
    newBrandCta: 'New brand',
    noChats: 'No chats yet',
    noChatsDetail: 'Start a chat for this brand.',
    loadingSessions: 'Updating sessions…',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteFolder: 'Delete folder',
    confirmDeleteFolder: 'Delete folder, chats, and offers',
    requestEdit: 'Request edit',
    optimizeForPost: 'Optimize for post',
    viewImage: 'View image',
    addReference: 'Add reference',
    imagesHint: 'Gallery for this offer. Generate posts from Create or chat. Request an edit to open a new chat.',
    noImagesYet: 'No images for this offer yet.',
    editReason: 'What should change?',
    editSessionSeed: 'Tell me the change and I’ll apply it to this image.',
    previewEnv: 'Preview',
    scriptsUsed: 'Scripts',
    imagesUsed: 'Images',
    quickGenerate: 'Quick generate',
    showLess: 'Show less',
    newSession: 'New session',
    useClassic: 'Return to classic dashboard',
    classicShort: 'Classic',
    assignToBrand: 'Assign to this brand',
    unassignedOffers: 'Unassigned products',
    openClassicHistory: 'Open classic history',
    deleteUnassigned: 'Delete unassigned product',
    clearUnassigned: 'Remove all unassigned',
    confirmClearUnassigned: 'Delete all unassigned products? This cannot be undone.',
  },
} as const

export function shellT(language: ChatShellLanguage) {
  return chatShellLabels[language] || chatShellLabels.es
}
