export type ChatShellLanguage = 'en' | 'es'

export const chatShellLabels = {
  es: {
    chat: 'Chat',
    context: 'Contexto',
    offers: 'Ofertas',
    images: 'Imágenes',
    brand: 'Marca',
    more: 'Más',
    create: 'Crear',
    createHint: 'Misma generación que el workspace anterior: configurá y generá. El chat sigue disponible.',
    generatePost: 'Generar post',
    closeRail: 'Cerrar panel',
    openRail: 'Abrir panel',
    workspace: 'Espacio',
    options: 'Opciones',
    backToWidget: 'Volver',
    openNav: 'Abrir navegación',
    closeNav: 'Cerrar navegación',
    noBrand: 'Sin marca',
    noSession: 'Sin sesión',
    noOffer: 'Sin oferta',
    newChat: 'Chat nuevo',
    newBrand: 'Nueva marca',
    settings: 'Configuración',
    signOut: 'Cerrar sesión',
    openTour: 'Cómo funciona',
    admin: 'Admin',
    scripts: 'Guiones',
    posts: 'Posts',
    descriptions: 'Descripciones',
    replies: 'Respuestas',
    askScripts: 'Pedí guiones…',
    askPost: 'Elegí tipo o tamaño del post…',
    askScriptType: 'Elegí el tipo de guion…',
    chooseOffers: 'Elegí ofertas en el panel, luego pedí un guión…',
    selectSession: 'Elegí una sesión para escribir',
    send: 'Enviar',
    you: 'Tú',
    generating: 'Generando',
    composer: 'Escribir mensaje',
    voice: 'Dictar mensaje',
    voiceStop: 'Detener grabación',
    voiceListening: 'Escuchando…',
    voiceTranscribing: 'Pasando a texto…',
    voiceUnsupported: 'El micrófono no está disponible en este navegador',
    attach: 'Adjuntar',
    attachLogo: 'Logo',
    attachReference: 'Referencia visual',
    attachDocument: 'Documento o PDF',
    attachProduct: 'Producto',
    attachContext: 'Contexto',
    attachDropHint: 'Soltá imágenes aquí',
    attachChipRemove: 'Quitar adjunto',
    attachRoleHint: 'Tocá para cambiar tipo',
    paletteSaved: 'Paleta guardada. La uso en las imágenes.',
    logoSaved: 'Logo guardado. Lo uso en los posts.',
    referenceSaved: 'Referencia guardada. La uso como guía visual en las imágenes.',
    attachSoon: 'Adjuntos próximamente',
    previewFooter: 'Plan',
    resumeSetup: 'Reanudar setup',
    improveSetup: 'Mejorar setup de la marca',
    retryFailed: 'Reintentar ofertas fallidas',
    failedOffers: 'Ofertas fallidas',
    loadingChat: 'Cargando chat…',
    loadingSession: 'Cargando sesión…',
    emptyThread: 'Escribí para generar guiones o imágenes.',
    bestModel: 'Mejor calidad',
    efficientModel: 'Más rápido',
    logo: 'Logo',
    productPhoto: 'Foto de producto',
    usage: 'Uso',
    openOffers: 'Abrir ofertas',
    linkedOffer: 'Esta oferta tiene piezas generadas. No se puede quitar.',
    brands: 'Marcas',
    loadingBrands: 'Cargando marcas…',
    noBrands: 'Sin marcas aún',
    noBrandsDetail: 'Creá tu primera marca para empezar a chatear.',
    newBrandCta: 'Nueva marca',
    noChats: 'Sin chats aún',
    noChatsDetail: 'Empezá un chat para esta marca.',
    loadingSessions: 'Actualizando sesiones…',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    deleteFolder: 'Eliminar carpeta',
    confirmDeleteFolder: 'Eliminar carpeta, chats y ofertas',
    requestEdit: 'Pedir edición',
    downloadImage: 'Descargar',
    optimizeForPost: 'Optimizar para post',
    viewImage: 'Ver imagen',
    addReference: 'Agregar referencia',
    imagesHint: 'Galería de esta oferta. Generá posts desde Crear o el chat. Pedí una edición para abrir un chat nuevo.',
    noImagesYet: 'Todavía no hay imágenes para esta oferta.',
    editReason: '¿Qué debería cambiar?',
    editSessionSeed: 'Decime el cambio y lo aplico sobre esta imagen.',
    previewEnv: 'Preview',
    scriptsUsed: 'Guiones',
    imagesUsed: 'Imágenes',
    creditsRemaining: 'Créditos IA',
    quickGenerate: 'Generar rápido',
    showLess: 'Ver menos',
    newSession: 'Nueva sesión',
    useClassic: 'Volver al panel clásico',
    classicShort: 'Clásico',
    assignToBrand: 'Asignar a esta marca',
    unassignedOffers: 'Productos sin marca',
    openClassicHistory: 'Ver historial clásico',
    deleteUnassigned: 'Eliminar producto sin marca',
    clearUnassigned: 'Eliminar todos los sin marca',
    confirmClearUnassigned: '¿Borrar todos los productos sin marca? Esta acción no se puede deshacer.',
    createOfferTitle: 'Nueva oferta',
    createOfferHint: 'Creá un producto u oferta para esta marca y lo adjuntamos a este chat.',
    offerNameLabel: 'Nombre de la oferta',
    offerNamePlaceholder: 'Ej. Plan Pro, Café de especialidad…',
    offerTypeLabel: 'Tipo',
    offerNameRequired: 'Escribí un nombre para la oferta.',
    createOfferAction: 'Crear y adjuntar',
    creatingOffer: 'Creando…',
    offersPrimary: 'Principal',
    offersAttachHint: 'Elegí hasta {max} productos. La posición 1 es la principal.',
    offersNoneAttached: 'Todavía no hay ofertas adjuntas.',
    offersMaxReached: 'Llegaste al máximo de {max} ofertas.',
    selectSessionOffers: 'Elegí una sesión para adjuntar ofertas.',
    sessionNoBusiness: 'Esta sesión no tiene marca — no se pueden adjuntar ofertas.',
    noBrandProducts: 'Esta marca no tiene productos. Creá uno abajo o asigná uno suelto.',
    showOlder: 'Ver {count} anteriores',
    quickSessionTag: 'Rápido',
    defaultSessionTitle: 'Chat nuevo',
    emptyNoSession: 'Elegí o creá una sesión bajo {brand}.',
    emptyNoBrand: 'Elegí una marca en la barra lateral (o creá una) para empezar.',
    emptyLoading: 'Cargando conversación…',
    emptyReadyWithOffer: 'Sesión lista · {detail}. Pedí un guion o una imagen para generar.',
    emptyReadyNoOffer: 'Sesión lista · todavía no hay oferta. Creá una en el panel Ofertas o confirmá el setup.',
    emptyExamplesHint: 'Probalo así',
    emptyExamplePrompts: [
      'Generame 2 guiones de venta directa',
      'Armá un post con foto del producto',
      'Contame un storytelling corto con CTA',
    ],
    emptyNeedOfferForScripts: 'Primero necesitás una oferta. Creala en Ofertas o confirmá el setup.',
    emptyFirstRunLine: 'Empezá por tu marca para generar guiones, posts y fotos.',
    emptyFirstRunCta: 'Empezá por tu marca',
    kitBlockedHint: 'Primero el kit',
    chooseOfferHint: 'Elegí oferta',
    openOffersPanel: 'Abrir ofertas',
    showCreateWidget: 'Mostrar Brand Kit',
    hideCreateWidget: 'Ocultar Brand Kit',
    reviewKit: 'Revisar Brand Kit',
    kitReady: 'Brand Kit listo',
    kitTitle: 'Brand Kit',
    kitNotReady: 'Brand Kit incompleto',
    kitNeedsTune: 'Falta afinar',
    createScriptsShort: 'Guiones',
    createPostShort: 'Post',
    createProductShort: 'Foto',
    createBulkShort: 'Pack',
    bulkTitle: 'Pack',
    bulkCopy: 'Ángulos distintos por nicho (no el mismo anuncio con otras palabras). Luego confirmás y generamos.',
    bulkCount: 'Cantidad (2–25)',
    bulkScriptsOnly: 'Solo guiones',
    bulkCampaign: 'Pack campaña',
    bulkStyleDna: 'Style DNA (opcional)',
    bulkStyleDnaNone: 'Sin DNA',
    bulkNeedBoard: 'Proponé el tablero de ángulos antes de confirmar.',
    bulkPropose: 'Proponer ángulos',
    bulkConfirm: 'Confirmar y generar',
    bulkQuote: 'Cotización máxima',
    bulkFailed: 'No se pudo generar el pack',
    flowBack: 'Atrás',
    flowScriptsTitle: 'Guiones',
    flowPostTitle: 'Post',
    flowFotoTitle: 'Foto',
    flowCreditsScript: '{n} créditos · {count} guion(es)',
    flowCreditsImage: '{n} créditos · imagen estándar',
    flowGenerate: 'Generar',
    flowContinue: 'Continuar',
    flowPickType: '¿Qué tipo de guiones querés crear?',
    flowPickCount: '¿Cuántas versiones necesitás?',
    flowPickCta: 'Elegí la mezcla de CTAs.',
    flowPickScript: 'Elegí el guion que querés convertir en post.',
    flowPickMode: '¿Anuncio, producto u orgánico?',
    flowPickAspect: '¿Qué tamaño? Reel, cuadrado o vertical.',
    flowPickDensity: '¿Cuánto texto en el post?',
    flowPickStyle: 'Elegí un estilo.',
    flowPickRefs: 'Confirmá referencias de producto, contexto y logo.',
    brandModalTitle: 'Nueva marca',
    brandModalCopy: 'Creá una marca y pegá la URL de tu tienda para arrancar el setup (o solo el nombre y lo completás en el chat).',
    brandModalName: 'Nombre de la marca',
    brandModalPlaceholder: 'Ej. Acme Studio',
    brandModalUrl: 'URL de la tienda (opcional)',
    brandModalUrlPlaceholder: 'Pegá la URL de tu tienda',
    brandModalUrlHint: 'Si la pegás acá, analizamos el sitio en cuanto se cree el chat.',
    brandModalCancel: 'Cancelar',
    brandModalCreate: 'Crear marca',
    brandModalCreating: 'Creando…',
    classicConfirm: '¿Volver al panel clásico? Podés regresar a Chat desde Configuración.',
    newBrandModalClose: 'Cerrar crear marca',
    sessionActionsFor: 'Acciones de la sesión',
    collapseBrand: 'Cerrar',
    expandBrand: 'Abrir',
    chatsCount: 'chats',
    navLabel: 'Navegación del chat',
    moveImageUp: 'Subir',
    moveImageDown: 'Bajar',
    removeImageRef: 'Quitar',
    imageOfferTablist: 'Oferta de imagen',
  },
  en: {
    chat: 'Chat',
    context: 'Context',
    offers: 'Offers',
    images: 'Images',
    brand: 'Brand',
    more: 'More',
    create: 'Create',
    createHint: 'Same generation as the previous workspace: configure and generate. Chat still works.',
    generatePost: 'Generate post',
    closeRail: 'Close panel',
    openRail: 'Open panel',
    workspace: 'Workspace',
    options: 'Options',
    backToWidget: 'Back',
    openNav: 'Open navigation',
    closeNav: 'Close navigation',
    noBrand: 'No brand',
    noSession: 'No session',
    noOffer: 'No offer',
    newChat: 'New chat',
    newBrand: 'New brand',
    settings: 'Settings',
    signOut: 'Sign out',
    openTour: 'How it works',
    admin: 'Admin',
    scripts: 'Scripts',
    posts: 'Posts',
    descriptions: 'Descriptions',
    replies: 'Replies',
    askScripts: 'Ask for scripts…',
    askPost: 'Pick the post type or size…',
    askScriptType: 'Pick a script type…',
    chooseOffers: 'Choose offers in Offers, then ask for a script…',
    selectSession: 'Select a session to compose',
    send: 'Send',
    you: 'You',
    generating: 'Generating',
    composer: 'Message composer',
    voice: 'Dictate message',
    voiceStop: 'Stop recording',
    voiceListening: 'Listening…',
    voiceTranscribing: 'Transcribing…',
    voiceUnsupported: 'Microphone is not available in this browser',
    attach: 'Attach',
    attachLogo: 'Logo',
    attachReference: 'Visual reference',
    attachDocument: 'Document or PDF',
    attachProduct: 'Product',
    attachContext: 'Context',
    attachDropHint: 'Drop images here',
    attachChipRemove: 'Remove attachment',
    attachRoleHint: 'Tap to change type',
    paletteSaved: 'Palette saved. I’ll use it on images.',
    logoSaved: 'Logo saved. I’ll use it on posts.',
    referenceSaved: 'Reference saved. I’ll use it as visual guidance on images.',
    attachSoon: 'Attachments coming soon',
    previewFooter: 'Plan',
    resumeSetup: 'Resume setup',
    improveSetup: 'Improve folder setup',
    retryFailed: 'Retry failed offers',
    failedOffers: 'Failed offers',
    loadingChat: 'Loading chat…',
    loadingSession: 'Loading session…',
    emptyThread: 'Ask for scripts or images to get started.',
    bestModel: 'Best quality',
    efficientModel: 'Faster',
    logo: 'Logo',
    productPhoto: 'Product photo',
    usage: 'Usage',
    openOffers: 'Open offers',
    linkedOffer: 'This offer has generated artifacts. It cannot be removed.',
    brands: 'Brands',
    loadingBrands: 'Loading brands…',
    noBrands: 'No brands yet',
    noBrandsDetail: 'Create your first brand to start chatting.',
    newBrandCta: 'New brand',
    noChats: 'No chats yet',
    noChatsDetail: 'Start a chat for this brand.',
    loadingSessions: 'Updating sessions…',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteFolder: 'Delete folder',
    confirmDeleteFolder: 'Delete folder, chats, and offers',
    requestEdit: 'Request edit',
    downloadImage: 'Download',
    optimizeForPost: 'Optimize for post',
    viewImage: 'View image',
    addReference: 'Add reference',
    imagesHint: 'Gallery for this offer. Generate posts from Create or chat. Request an edit to open a new chat.',
    noImagesYet: 'No images for this offer yet.',
    editReason: 'What should change?',
    editSessionSeed: 'Tell me the change and I’ll apply it to this image.',
    previewEnv: 'Preview',
    scriptsUsed: 'Scripts',
    imagesUsed: 'Images',
    creditsRemaining: 'AI credits',
    quickGenerate: 'Quick generate',
    showLess: 'Show less',
    newSession: 'New session',
    useClassic: 'Return to classic dashboard',
    classicShort: 'Classic',
    assignToBrand: 'Assign to this brand',
    unassignedOffers: 'Unassigned products',
    openClassicHistory: 'Open classic history',
    deleteUnassigned: 'Delete unassigned product',
    clearUnassigned: 'Remove all unassigned',
    confirmClearUnassigned: 'Delete all unassigned products? This cannot be undone.',
    createOfferTitle: 'New offer',
    createOfferHint: 'Create a product or offer for this brand and attach it to this chat.',
    offerNameLabel: 'Offer name',
    offerNamePlaceholder: 'e.g. Pro Plan, Specialty coffee…',
    offerTypeLabel: 'Type',
    offerNameRequired: 'Enter a name for the offer.',
    createOfferAction: 'Create and attach',
    creatingOffer: 'Creating…',
    offersPrimary: 'Primary',
    offersAttachHint: 'Select up to {max} products. Position 1 is primary.',
    offersNoneAttached: 'No offers attached yet.',
    offersMaxReached: 'Maximum of {max} offers reached.',
    selectSessionOffers: 'Select a session to attach product offers.',
    sessionNoBusiness: 'This session has no brand — cannot attach offers.',
    noBrandProducts: 'This brand has no products yet. Create one below or assign an unassigned product.',
    showOlder: 'Show {count} older',
    quickSessionTag: 'Quick',
    defaultSessionTitle: 'New chat',
    emptyNoSession: 'Select or create a session under {brand}.',
    emptyNoBrand: 'Select a brand in the sidebar (or create one) to get started.',
    emptyLoading: 'Loading conversation…',
    emptyReadyWithOffer: 'Session ready · {detail}. Ask for a script or image to generate.',
    emptyReadyNoOffer: 'Session ready · no offer yet. Create one in Offers or confirm setup.',
    emptyExamplesHint: 'Try one of these',
    emptyExamplePrompts: [
      'Generate 2 direct-sale scripts',
      'Make a post with a product photo',
      'Write a short storytelling script with a CTA',
    ],
    emptyNeedOfferForScripts: 'You need an offer first. Create one in Offers or confirm setup.',
    emptyFirstRunLine: 'Start with your brand to generate scripts, posts, and photos.',
    emptyFirstRunCta: 'Start with your brand',
    kitBlockedHint: 'Kit first',
    chooseOfferHint: 'Choose offer',
    openOffersPanel: 'Open offers',
    showCreateWidget: 'Show Brand Kit',
    hideCreateWidget: 'Hide Brand Kit',
    reviewKit: 'Review Brand Kit',
    kitReady: 'Brand Kit ready',
    kitTitle: 'Brand Kit',
    kitNotReady: 'Brand Kit incomplete',
    kitNeedsTune: 'Needs a tune-up',
    createScriptsShort: 'Scripts',
    createPostShort: 'Post',
    createProductShort: 'Photo',
    createBulkShort: 'Pack',
    bulkTitle: 'Pack',
    bulkCopy: 'Distinct buyer-niche angles (not the same ad in different words). Confirm, then we generate.',
    bulkCount: 'Count (2–25)',
    bulkScriptsOnly: 'Scripts only',
    bulkCampaign: 'Campaign pack',
    bulkStyleDna: 'Style DNA (optional)',
    bulkStyleDnaNone: 'No DNA',
    bulkNeedBoard: 'Propose the angle board before confirming.',
    bulkPropose: 'Propose angles',
    bulkConfirm: 'Confirm and generate',
    bulkQuote: 'Maximum quote',
    bulkFailed: 'Could not generate the pack',
    flowBack: 'Back',
    flowScriptsTitle: 'Scripts',
    flowPostTitle: 'Post',
    flowFotoTitle: 'Photo',
    flowCreditsScript: '{n} credits · {count} script(s)',
    flowCreditsImage: '{n} credits · standard image',
    flowGenerate: 'Generate',
    flowContinue: 'Continue',
    flowPickType: 'What kind of scripts do you want?',
    flowPickCount: 'How many versions do you need?',
    flowPickCta: 'Choose the CTA mix.',
    flowPickScript: 'Choose the script you want to turn into a post.',
    flowPickMode: 'Ad, product, or organic?',
    flowPickAspect: 'What size? Reel, square, or vertical.',
    flowPickDensity: 'How much copy on the post?',
    flowPickStyle: 'Pick a style.',
    flowPickRefs: 'Confirm product, context, and logo references.',
    brandModalTitle: 'New brand',
    brandModalCopy: 'Create a brand and paste your store URL to start setup (or just a name and finish in chat).',
    brandModalName: 'Brand name',
    brandModalPlaceholder: 'e.g. Acme Studio',
    brandModalUrl: 'Store URL (optional)',
    brandModalUrlPlaceholder: 'Paste your store URL',
    brandModalUrlHint: 'If you paste it here, we analyze the site as soon as the chat is created.',
    brandModalCancel: 'Cancel',
    brandModalCreate: 'Create brand',
    brandModalCreating: 'Creating…',
    classicConfirm: 'Return to the classic dashboard? You can come back to Chat from Settings.',
    newBrandModalClose: 'Close create brand',
    sessionActionsFor: 'Session actions for',
    collapseBrand: 'Collapse',
    expandBrand: 'Expand',
    chatsCount: 'chats',
    navLabel: 'Chat navigation',
    moveImageUp: 'Move up',
    moveImageDown: 'Move down',
    removeImageRef: 'Remove',
    imageOfferTablist: 'Image offer',
  },
} as const

export function shellT(language: ChatShellLanguage) {
  return chatShellLabels[language] || chatShellLabels.es
}

/** Ad Pack studio (Marca → Ángulos → Resultados). Same es/en pattern as `chatShellLabels`. */
export const adPackStudioLabels = {
  es: {
    title: 'Pack de anuncios',
    subtitle: 'Tu marca, ángulos distintos y anuncios listos para publicar.',
    close: 'Cerrar',
    back: 'Atrás',
    steps: ['Marca', 'Ángulos', 'Resultados'],
    stepOf: (n: number, total: number) => `Paso ${n} de ${total}`,
    sourcesHeading: 'Fuentes',
    website: 'Sitio web',
    websitePlaceholder: 'https://tumarca.com',
    instagram: 'Instagram',
    instagramPlaceholder: 'https://instagram.com/tumarca',
    offerName: 'Producto u oferta',
    offerNamePlaceholder: 'Ej.: Café de altura 340 g',
    productPhotos: 'Fotos del producto',
    productPhotosHint: 'La primera es la principal. Fondo limpio = mejores escenas.',
    logo: 'Logo',
    references: 'Capturas de tu Instagram / reseñas / anuncios de referencia',
    referencesHint: 'Subí 3–5 capturas: mejoran el tono, las frases de clientes y el estilo.',
    addFiles: 'Agregar',
    removeFile: (name: string) => `Quitar ${name}`,
    uploading: 'Subiendo…',
    uploadFailed: 'No se pudo subir',
    tooManyUploads: (max: number) => `Máximo ${max} archivos.`,
    badFileType: 'Solo imágenes PNG, JPEG o WebP de hasta 10 MB.',
    switchKind: 'Cambiar tipo',
    analyze: 'Analizar',
    reanalyze: 'Volver a analizar',
    analyzing: 'Analizando…',
    analyzingSteps: ['Leyendo tu sitio…', 'Revisando Instagram…', 'Mirando tus capturas…', 'Armando el ADN de marca…'],
    needSource: 'Agregá un sitio, Instagram o al menos una imagen para analizar.',
    dnaEmpty: 'Agregá tus fuentes y tocá “Analizar”. Vas a revisar cada dato antes de generar.',
    dnaHeading: 'ADN de marca',
    category: 'Categoría',
    voice: 'Voz',
    audience: 'Audiencia',
    factsHeading: 'Datos',
    factsExplain: 'Solo los datos confirmados se usan como afirmaciones en los anuncios (precios, envíos, garantías).',
    confirm: 'Confirmar',
    confirmedCount: (n: number, total: number) => `${n} de ${total} confirmados`,
    gapsAdd: 'Falta',
    gapPlaceholder: (label: string) => `Escribí ${label.toLowerCase()}`,
    sourcesStatus: 'Estado de fuentes',
    sourceOk: 'leído',
    sourceFailed: 'no disponible',
    continue: 'Continuar',
    confirming: 'Guardando…',
    anglesHeading: 'Ángulos',
    anglesCopy: 'Cada anuncio vende un mensaje distinto. Apagá los que no quieras.',
    packSize: 'Cantidad de anuncios',
    less: 'Menos',
    more: 'Más',
    planning: 'Planeando ángulos…',
    ratios: 'Formatos',
    ratioNames: { '1:1': 'Cuadrado', '4:5': 'Feed', '9:16': 'Historia' } as Record<string, string>,
    needRatio: 'Elegí al menos un formato.',
    target: 'Para',
    angleOn: (n: number) => `Incluir ángulo ${n}`,
    selected: (n: number, total: number) => `${n} de ${total} seleccionados`,
    minAngles: 'Elegí al menos un ángulo.',
    generate: 'Generar',
    starting: 'Iniciando…',
    insufficient: (need: number, have?: number) =>
      have == null
        ? `No tenés créditos suficientes: este pack necesita ${need}.`
        : `No tenés créditos suficientes: este pack necesita ${need} y te quedan ${have}.`,
    creditsLeft: (n: number) => `te quedan ${n}`,
    resultsHeading: 'Resultados',
    keepsRunning: 'El pack sigue generándose aunque cierres esta ventana.',
    cancelPack: 'Cancelar pack',
    cancelConfirm: '¿Cancelar el pack? Los anuncios listos se conservan.',
    cancelling: 'Cancelando…',
    downloadAll: 'Descargar todo',
    downloading: (n: number, total: number) => `Descargando ${n}/${total}…`,
    copyCaptions: 'Copiar captions',
    copied: 'Copiado',
    copyFailed: 'No se pudo copiar',
    reconnecting: 'Reconectando…',
    packNotFound: 'No encontramos este pack de anuncios. Puede que el enlace esté mal o que el pack sea de otra cuenta.',
    newPack: 'Nuevo pack',
    ratioTabs: 'Formato del anuncio',
    open: 'Ampliar',
    openAd: (n: number) => `Ampliar anuncio ${n}`,
    editText: 'Editar texto',
    headline: 'Titular',
    subline: 'Subtítulo',
    cta: 'CTA',
    bullets: 'Viñetas (una por línea)',
    save: 'Guardar',
    saving: 'Guardando…',
    cancel: 'Cancelar',
    noChanges: 'No hay cambios.',
    rejected: 'No se puede usar ese texto:',
    regenerate: 'Regenerar',
    regenScene: 'Nueva escena (mismo texto)',
    regenCopy: 'Nuevo texto y escena',
    regenCost: (n: number) => `Cuesta ${n} créditos.`,
    regenConfirm: 'Confirmar',
    download: 'Descargar PNG',
    copyCaption: 'Copiar caption',
    busy: 'Este anuncio todavía se está generando.',
    closePreview: 'Cerrar vista',
    adLabel: (n: number) => `Anuncio ${n}`,
  },
  en: {
    title: 'Ad pack',
    subtitle: 'Your brand, distinct angles and ads ready to post.',
    close: 'Close',
    back: 'Back',
    steps: ['Brand', 'Angles', 'Results'],
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    sourcesHeading: 'Sources',
    website: 'Website',
    websitePlaceholder: 'https://yourbrand.com',
    instagram: 'Instagram',
    instagramPlaceholder: 'https://instagram.com/yourbrand',
    offerName: 'Product or offer',
    offerNamePlaceholder: 'e.g. Single-origin coffee 340 g',
    productPhotos: 'Product photos',
    productPhotosHint: 'The first one is the hero. Clean backgrounds = better scenes.',
    logo: 'Logo',
    references: 'Instagram screenshots / reviews / reference ads',
    referencesHint: 'Upload 3–5 screenshots: they improve tone, customer phrases and style.',
    addFiles: 'Add',
    removeFile: (name: string) => `Remove ${name}`,
    uploading: 'Uploading…',
    uploadFailed: 'Upload failed',
    tooManyUploads: (max: number) => `At most ${max} files.`,
    badFileType: 'Only PNG, JPEG or WebP images up to 10 MB.',
    switchKind: 'Change type',
    analyze: 'Analyze',
    reanalyze: 'Analyze again',
    analyzing: 'Analyzing…',
    analyzingSteps: ['Reading your site…', 'Checking Instagram…', 'Looking at your screenshots…', 'Building the brand DNA…'],
    needSource: 'Add a website, Instagram or at least one image to analyze.',
    dnaEmpty: 'Add your sources and tap “Analyze”. You will review every fact before generating.',
    dnaHeading: 'Brand DNA',
    category: 'Category',
    voice: 'Voice',
    audience: 'Audience',
    factsHeading: 'Facts',
    factsExplain: 'Only confirmed facts are used as claims in the ads (prices, shipping, guarantees).',
    confirm: 'Confirm',
    confirmedCount: (n: number, total: number) => `${n} of ${total} confirmed`,
    gapsAdd: 'Missing',
    gapPlaceholder: (label: string) => `Enter ${label.toLowerCase()}`,
    sourcesStatus: 'Source status',
    sourceOk: 'read',
    sourceFailed: 'unavailable',
    continue: 'Continue',
    confirming: 'Saving…',
    anglesHeading: 'Angles',
    anglesCopy: 'Each ad sells a different message. Turn off the ones you do not want.',
    packSize: 'Number of ads',
    less: 'Fewer',
    more: 'More',
    planning: 'Planning angles…',
    ratios: 'Formats',
    ratioNames: { '1:1': 'Square', '4:5': 'Feed', '9:16': 'Story' } as Record<string, string>,
    needRatio: 'Pick at least one format.',
    target: 'For',
    angleOn: (n: number) => `Include angle ${n}`,
    selected: (n: number, total: number) => `${n} of ${total} selected`,
    minAngles: 'Pick at least one angle.',
    generate: 'Generate',
    starting: 'Starting…',
    insufficient: (need: number, have?: number) =>
      have == null
        ? `Not enough credits: this pack needs ${need}.`
        : `Not enough credits: this pack needs ${need} and you have ${have}.`,
    creditsLeft: (n: number) => `${n} left`,
    resultsHeading: 'Results',
    keepsRunning: 'The pack keeps generating even if you close this window.',
    cancelPack: 'Cancel pack',
    cancelConfirm: 'Cancel the pack? Finished ads are kept.',
    cancelling: 'Cancelling…',
    downloadAll: 'Download all',
    downloading: (n: number, total: number) => `Downloading ${n}/${total}…`,
    copyCaptions: 'Copy captions',
    copied: 'Copied',
    copyFailed: 'Could not copy',
    reconnecting: 'Reconnecting…',
    packNotFound: "We couldn't find this ad pack. The link may be wrong or the pack may belong to another account.",
    newPack: 'New pack',
    ratioTabs: 'Ad format',
    open: 'Enlarge',
    openAd: (n: number) => `Enlarge ad ${n}`,
    editText: 'Edit text',
    headline: 'Headline',
    subline: 'Subline',
    cta: 'CTA',
    bullets: 'Bullets (one per line)',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    noChanges: 'No changes.',
    rejected: 'That text cannot be used:',
    regenerate: 'Regenerate',
    regenScene: 'New scene (same text)',
    regenCopy: 'New text and scene',
    regenCost: (n: number) => `Costs ${n} credits.`,
    regenConfirm: 'Confirm',
    download: 'Download PNG',
    copyCaption: 'Copy caption',
    busy: 'This ad is still being generated.',
    closePreview: 'Close preview',
    adLabel: (n: number) => `Ad ${n}`,
  },
}

export type AdPackStudioLabels = (typeof adPackStudioLabels)['es']

export function adPackT(language: ChatShellLanguage): AdPackStudioLabels {
  return adPackStudioLabels[language] || adPackStudioLabels.es
}
