export type ChangeCategory = 'feature' | 'fix' | 'improvement' | 'rework'
export type RoadmapStatus = 'planned' | 'in_progress' | 'beta' | 'done'

export interface ChangelogEntry {
  version: string
  date: string // YYYY-MM-DD
  items: {
    category: ChangeCategory
    text: { es: string; en: string }
  }[]
}

export interface RoadmapItem {
  status: RoadmapStatus
  text: { es: string; en: string }
  eta?: string
}

export interface StatusAlert {
  active: boolean
  text: { es: string; en: string }
  severity: 'info' | 'warning' | 'error'
}

// =============================================
// STATUS ALERT — show if a feature is having issues
// Set active: false to hide
// =============================================
export const STATUS_ALERT: StatusAlert = {
  active: false,
  text: {
    es: 'La generación de imágenes puede tardar más de lo normal. Estamos trabajando en ello.',
    en: 'Image generation may be slower than usual. We are working on it.'
  },
  severity: 'info'
}

// =============================================
// ROADMAP — what's coming next
// =============================================
export const ROADMAP: RoadmapItem[] = [
  {
    status: 'done',
    text: {
      es: 'Brand Kit — identidad visual y tonal aplicada automáticamente',
      en: 'Brand Kit — auto-applied visual and tonal identity'
    }
  },
  {
    status: 'in_progress',
    text: {
      es: 'Fondos temáticos — mármol, madera, naturaleza, navidad y más como presets rápidos',
      en: 'Background theme presets — marble, wood, nature, Christmas and more as quick picks'
    },
    eta: 'Mar 2026'
  },
  {
    status: 'planned',
    text: {
      es: 'Catálogo de producto — genera sets consistentes de fotos para toda tu línea',
      en: 'Product catalog — generate consistent photo sets for your entire product line'
    }
  },
  {
    status: 'planned',
    text: {
      es: 'Analíticas de rendimiento — métricas de tus guiones y posts',
      en: 'Performance analytics — metrics for your scripts and posts'
    }
  },
  {
    status: 'planned',
    text: {
      es: 'Plantillas de guiones — guarda y reutiliza estructuras que funcionan',
      en: 'Script templates — save and reuse structures that work'
    }
  }
]

// =============================================
// CHANGELOG — add new entries at the TOP
// =============================================
//
// EDITORIAL GUIDELINES (for developers / AI assistants):
// 1. NEVER include admin-only changes (admin dashboard, admin routes, internal tooling).
// 2. NEVER expose security fixes in detail — omit them entirely or use vague
//    user-facing language like "Mejoras generales de estabilidad" / "General stability improvements".
// 3. Only list changes that are visible or meaningful to end users.
// 4. Keep language simple, non-technical, and benefit-oriented.
// 5. Do NOT mention internal architecture, database migrations, or RLS policies.
//
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '0.1.3',
    date: '2026-03-06',
    items: [
      {
        category: 'fix',
        text: {
          es: 'La app ya no se recarga al cambiar de pestaña o volver de otra aplicación — tu trabajo se mantiene intacto',
          en: 'The app no longer reloads when switching tabs or returning from another application — your work stays intact'
        }
      },
      {
        category: 'improvement',
        text: {
          es: 'Navegación más fluida — menos tiempos de carga innecesarios al moverte entre secciones',
          en: 'Smoother navigation — fewer unnecessary loading times when moving between sections'
        }
      },
      {
        category: 'improvement',
        text: {
          es: 'Optimización para móvil — la app ahora funciona correctamente desde el teléfono',
          en: 'Mobile optimization — the app now works properly on phone'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Guión optimizado ahora es editable — ajusta el prompt generado por "Optimizar para post" antes de generar',
          en: 'Optimized script is now editable — tweak the prompt generated by "Optimize for post" before generating'
        }
      }
    ]
  },
  {
    version: '0.1.2',
    date: '2026-02-27',
    items: [
      {
        category: 'feature',
        text: {
          es: 'Foto de Producto — nuevo tipo de post para fotografía profesional de producto con IA',
          en: 'Product Photo — new post type for AI-powered professional product photography'
        }
      },
      {
        category: 'feature',
        text: {
          es: '6 estilos de foto: Estudio Hero, Lifestyle, Cambiar Fondo, Solo Mejorar, Splash/Acción y Podio 3D',
          en: '6 photo styles: Studio Hero, Lifestyle, Background Swap, Pure Enhancement, Splash/Action and 3D Podium'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Formato cuadrado (1:1) disponible en modo Producto — ideal para e-commerce y catálogos',
          en: 'Square format (1:1) available in Product mode — ideal for e-commerce and catalogs'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Descripción de cliente ideal — pega un texto detallado de tu ICP en tu negocio para que la IA lo use en todo el contenido',
          en: 'Ideal customer description — paste a detailed ICP text in your business so the AI uses it across all content'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Brand Kit — define colores, voz y frases de tu marca en Configuración',
          en: 'Brand Kit — define brand colors, voice and phrases in Settings'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Sección "Desde el Desarrollador" — changelog, roadmap y feedback',
          en: '"From the Developer" section — changelog, roadmap and feedback'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Instrucciones adicionales al generar posts — guía el estilo y diseño con texto libre',
          en: 'Additional instructions when generating posts — guide style and design with free text'
        }
      },
      {
        category: 'improvement',
        text: {
          es: 'Los ratings de guiones ahora se guardan y persisten entre sesiones',
          en: 'Script ratings now persist across sessions'
        }
      },
      {
        category: 'improvement',
        text: {
          es: 'Ratings positivos ahora también mejoran la memoria de IA',
          en: 'Positive ratings now also improve AI memory'
        }
      },
      {
        category: 'improvement',
        text: {
          es: 'Ahora puedes ver el uso de respuestas en tu resumen del plan',
          en: 'Reply usage now visible in your plan summary'
        }
      },
      {
        category: 'fix',
        text: {
          es: 'Corrección de formato cuadrado en prompts de fotografía de producto',
          en: 'Fixed square format label in product photography prompts'
        }
      },
      {
        category: 'improvement',
        text: {
          es: 'Mejoras generales de estabilidad y rendimiento',
          en: 'General stability and performance improvements'
        }
      }
    ]
  },
  {
    version: '0.1.1',
    date: '2026-02-23',
    items: [
      {
        category: 'feature',
        text: {
          es: 'Estilos de post personalizados — sube referencias y crea tu propio estilo',
          en: 'Custom post styles — upload references and create your own style'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Respuestas a clientes (Respuestas) — genera respuestas de venta con IA',
          en: 'Client replies (Respuestas) — generate AI-powered sales replies'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Varita mágica — mejora posts generados con un click',
          en: 'Magic wand — enhance generated posts with one click'
        }
      }
    ]
  },
  {
    version: '0.1.0',
    date: '2026-02-16',
    items: [
      {
        category: 'feature',
        text: {
          es: '8 presets de estilo para posts (Features, Showcase, Social Proof, etc.)',
          en: '8 post style presets (Features, Showcase, Social Proof, etc.)'
        }
      },
      {
        category: 'feature',
        text: {
          es: 'Paletas de colores predefinidas y personalizadas para posts',
          en: 'Predefined and custom color palettes for posts'
        }
      },
      {
        category: 'improvement',
        text: {
          es: 'Edición de imágenes con IA — modifica posts generados con instrucciones',
          en: 'AI image editing — modify generated posts with instructions'
        }
      }
    ]
  }
]
