/**
 * Auto-generated by analyze_templates.py
 * Generated: 2026-02-16 15:42:45
 * Source: 356 social media ad template images across 8 categories
 *
 * DO NOT EDIT MANUALLY - regenerate by running analyze_templates.py
 */

export interface ImagePreset {
  id: string;
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  thumbnails: string[];
  masterPrompt: string;
  masterPromptEs: string;
  suggestedAspectRatios: string[];
  tags: string[];
  totalTemplates: number;
}

export const IMAGE_PRESETS: ImagePreset[] = [
  {
    id: "features-benefits",
    name: "Features & Benefits",
    nameEs: "Características y Beneficios",
    description: "Product-centered hero with callout labels and arrows pointing to specific features.",
    descriptionEs: "Imagen principal del producto con etiquetas y flechas señalando características específicas.",
    thumbnails: ["/presets/01_Features_Benefits/020_Access_183.png", "/presets/01_Features_Benefits/040_Access_278.png", "/presets/01_Features_Benefits/059_Access_406-407.png", "/presets/01_Features_Benefits/001_template.png"],
    masterPrompt: `Social Media Ad Template: Features & Benefits Style. Create a visually appealing social media ad template. Layout: Feature a central product hero shot, slightly off-center. Arrange 3-4 callout labels (rounded rectangles) around the product, connected by thin arrows pointing to specific features. Color Palette: Use a soft, pastel color palette. Background should be a solid light cream color (#F5F5DC). Use a desaturated blue (#ADD8E6) for the callout labels and a slightly darker blue (#87CEEB) for the arrows. Typography: Use a clean, modern sans-serif font like Open Sans or Lato. Headline: Bold, mixed-case, placed above the product. Callout Label Text: Regular weight, mixed-case, concise descriptions of the product benefits. Visual Elements: Include a high-quality product photo with soft lighting. Use simple, minimalist icons within the callout labels to visually represent each benefit. Composition: Ensure a clear visual hierarchy. The product should be the focal point, followed by the headline and callout labels. Use whitespace effectively to create a sense of spaciousness. Mood: Clean, modern, trustworthy, and informative. The ad should feel professional and approachable. Add a subtle shadow under the product to give it depth. Include a small brand logo in the top right corner. Add a call to action button at the bottom in a contrasting color (e.g., light orange #FFA07A).`,
    masterPromptEs: `Plantilla de anuncio para redes sociales: Estilo Características y Beneficios. Crea una plantilla de anuncio visualmente atractiva para redes sociales. Diseño: Presenta una imagen principal del producto centrada, ligeramente descentrada. Organiza de 3 a 4 etiquetas de llamada (rectángulos redondeados) alrededor del producto, conectadas por flechas delgadas que apuntan a características específicas. Paleta de colores: Utiliza una paleta de colores pastel suave. El fondo debe ser de un color crema claro sólido (#F5F5DC). Utiliza un azul desaturado (#ADD8E6) para las etiquetas de llamada y un azul ligeramente más oscuro (#87CEEB) para las flechas. Tipografía: Utiliza una fuente sans-serif limpia y moderna como Open Sans o Lato. Título: Negrita, mayúsculas y minúsculas, colocado encima del producto. Texto de la etiqueta de llamada: Peso normal, mayúsculas y minúsculas, descripciones concisas de los beneficios del producto. Elementos visuales: Incluye una foto de alta calidad del producto con iluminación suave. Utiliza iconos simples y minimalistas dentro de las etiquetas de llamada para representar visualmente cada beneficio. Composición: Asegura una jerarquía visual clara. El producto debe ser el punto focal, seguido del título y las etiquetas de llamada. Utiliza el espacio en blanco de manera efectiva para crear una sensación de amplitud. Ambiente: Limpio, moderno, confiable e informativo. El anuncio debe sentirse profesional y accesible. Agrega una sombra sutil debajo del producto para darle profundidad. Incluye un pequeño logotipo de la marca en la esquina superior derecha. Agrega un botón de llamada a la acción en la parte inferior en un color contrastante (por ejemplo, naranja claro #FFA07A).`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["clean", "modern", "minimalist", "informative", "trustworthy", "pastel", "product-focused"],
    totalTemplates: 78,
  },
  {
    id: "product-showcase",
    name: "Product Showcase",
    nameEs: "Exhibición de Producto",
    description: "Clean product-centered layout with bright colors and callout labels for key features.",
    descriptionEs: "Diseño limpio centrado en el producto con colores brillantes y etiquetas de características clave.",
    thumbnails: ["/presets/02_Product_Showcase/018_Access_132.png", "/presets/02_Product_Showcase/036_Access_204.png", "/presets/02_Product_Showcase/053_Access_310-311.png", "/presets/02_Product_Showcase/001_template.png"],
    masterPrompt: `Product Showcase Ad Style: Create a visually appealing social media ad template in a clean and modern style. The layout should feature a prominent product photo as the central element. Use a bright and inviting color palette, such as a combination of teal (#008080) and light yellow (#FFFFE0), or a gradient background transitioning from light pink (#FFB6C1) to white (#FFFFFF). Employ a sans-serif font like Open Sans or Montserrat for all text elements. The headline should be bold and uppercase, placed above the product image. Use a smaller, regular-weight font for the body text, positioned below the image. Incorporate callout labels with rounded corners to highlight key product features, using a contrasting color like orange (#FFA500) or dark green (#006400). Add subtle arrows or lines to connect the callout labels to the corresponding product features. Include a clear call-to-action button with a contrasting background color, using text like 'Shop Now' or 'Learn More'. Maintain a clean and balanced composition with ample whitespace. The overall mood should be trustworthy and inviting, showcasing the product's benefits in a clear and concise manner. Aspect ratio should be 1:1 or 4:5.`,
    masterPromptEs: `Estilo de Anuncio de Exhibición de Productos: Crea una plantilla de anuncio para redes sociales visualmente atractiva con un estilo limpio y moderno. El diseño debe presentar una foto destacada del producto como elemento central. Utiliza una paleta de colores brillante y atractiva, como una combinación de verde azulado (#008080) y amarillo claro (#FFFFE0), o un fondo degradado que haga transición de rosa claro (#FFB6C1) a blanco (#FFFFFF). Emplea una fuente sans-serif como Open Sans o Montserrat para todos los elementos de texto. El titular debe ser en negrita y en mayúsculas, colocado encima de la imagen del producto. Utiliza una fuente más pequeña y de peso normal para el cuerpo del texto, ubicado debajo de la imagen. Incorpora etiquetas de llamada con esquinas redondeadas para resaltar las características clave del producto, utilizando un color contrastante como naranja (#FFA500) o verde oscuro (#006400). Agrega flechas o líneas sutiles para conectar las etiquetas de llamada a las características correspondientes del producto. Incluye un botón claro de llamada a la acción con un color de fondo contrastante, utilizando texto como 'Comprar Ahora' o 'Aprender Más'. Mantén una composición limpia y equilibrada con amplio espacio en blanco. El ambiente general debe ser confiable y atractivo, mostrando los beneficios del producto de manera clara y concisa. La relación de aspecto debe ser 1:1 o 4:5.`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["product", "clean", "modern", "bright", "minimal", "showcase", "trustworthy"],
    totalTemplates: 70,
  },
  {
    id: "social-proof",
    name: "Social Proof",
    nameEs: "Prueba Social",
    description: "Split-screen with product photo and customer testimonial, star ratings, social media interfaces.",
    descriptionEs: "Pantalla dividida con foto del producto y testimonio del cliente, calificaciones, interfaces sociales.",
    thumbnails: ["/presets/03_Social_Proof/007_Access_93.png", "/presets/03_Social_Proof/014_Access_282.png", "/presets/03_Social_Proof/021_template.png", "/presets/03_Social_Proof/001_template.png"],
    masterPrompt: `Social Proof Ad Template: Create a social media ad image in a clean, modern style. Use a split-screen layout with a product photo on the left and a customer testimonial on the right. The color palette should be high-contrast, using a clean white background with a bold accent color like teal. Typography should be sans-serif, with a bold headline in uppercase and a smaller, readable body text. Include a high-quality product photo with professional lighting and styling. The customer testimonial should be concise and impactful, with the customer's name and photo included. Add a callout label with a key benefit highlighted in the accent color. Use arrows or lines to connect the product photo to the testimonial. Include star ratings to showcase customer satisfaction. The composition should be balanced and visually appealing, with whitespace used effectively to create a clean look. The overall mood should be trustworthy, modern, and professional. Simulate a social media interface by including a small profile icon and timestamp near the testimonial. Add a subtle drop shadow to the headline for emphasis. Ensure all elements are aligned for a polished, professional look. The aspect ratio should be 4:5.`,
    masterPromptEs: `Plantilla de anuncio de prueba social: Crea una imagen de anuncio para redes sociales con un estilo limpio y moderno. Utiliza un diseño de pantalla dividida con una foto del producto a la izquierda y un testimonio del cliente a la derecha. La paleta de colores debe ser de alto contraste, utilizando un fondo blanco limpio con un color de acento llamativo como el verde azulado. La tipografía debe ser sans-serif, con un titular en negrita en mayúsculas y un texto de cuerpo más pequeño y legible. Incluye una foto de producto de alta calidad con iluminación y estilo profesionales. El testimonio del cliente debe ser conciso e impactante, con el nombre y la foto del cliente incluidos. Agrega una etiqueta de llamada con un beneficio clave resaltado en el color de acento. Utiliza flechas o líneas para conectar la foto del producto con el testimonio. Incluye calificaciones de estrellas para mostrar la satisfacción del cliente. La composición debe ser equilibrada y visualmente atractiva, con espacios en blanco utilizados eficazmente para crear una apariencia limpia. El ambiente general debe ser confiable, moderno y profesional. Simula una interfaz de redes sociales incluyendo un pequeño icono de perfil y una marca de tiempo cerca del testimonio. Agrega una sombra sutil al titular para dar énfasis. Asegúrate de que todos los elementos estén alineados para una apariencia pulida y profesional. La relación de aspecto debe ser 4:5.`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["clean", "modern", "trustworthy", "professional", "high-contrast", "minimalist", "balanced"],
    totalTemplates: 27,
  },
  {
    id: "comparison",
    name: "Comparison",
    nameEs: "Comparación",
    description: "Split-screen comparison with VS element, contrasting sections for two products or options.",
    descriptionEs: "Comparación en pantalla dividida con elemento VS, secciones contrastantes para dos opciones.",
    thumbnails: ["/presets/04_Comparison/014_Access_71.png", "/presets/04_Comparison/021_Access_312-313.png", "/presets/04_Comparison/007_template.png", "/presets/04_Comparison/001_template.png"],
    masterPrompt: `Comparison Ad Template: Create a social media ad image in a split-screen comparison style. Divide the image vertically into two equal sections. Use a pastel color palette: light blue (#ADD8E6) for the left section and light pink (#FFB6C1) for the right section. The background should be a solid, light gray (#F0F0F0). In the center, place a 'VS' icon in a circle with a thin black border. On the left, display a product photo of [Product A] centered in the section. On the right, display a product photo of [Product B] centered in the section. Use a clean, sans-serif font like Open Sans. The headline for each section should be in bold, uppercase letters, size 36pt, and placed above the product photo. Below each product photo, list 3-4 comparison points using checkmarks (green, #008000) for positive attributes and crosses (red, #FF0000) for negative attributes. Use a font size of 24pt for the comparison points. The overall composition should be balanced and clean, with ample whitespace. The mood should be informative, trustworthy, and modern. Include a thin black border around the entire image. Ensure the layout is clear and easy to understand, guiding the viewer's eye from left to right. Add a subtle shadow effect beneath the product images to give them depth.`,
    masterPromptEs: `Plantilla de anuncio comparativo: Crea una imagen de anuncio para redes sociales en un estilo de comparación de pantalla dividida. Divide la imagen verticalmente en dos secciones iguales. Utiliza una paleta de colores pastel: azul claro (#ADD8E6) para la sección izquierda y rosa claro (#FFB6C1) para la sección derecha. El fondo debe ser un gris claro sólido (#F0F0F0). En el centro, coloca un icono 'VS' en un círculo con un borde negro delgado. A la izquierda, muestra una foto del producto [Producto A] centrada en la sección. A la derecha, muestra una foto del producto [Producto B] centrada en la sección. Utiliza una fuente sans-serif limpia como Open Sans. El titular de cada sección debe estar en negrita, en mayúsculas, tamaño 36pt, y colocado encima de la foto del producto. Debajo de cada foto del producto, enumera 3-4 puntos de comparación utilizando marcas de verificación (verde, #008000) para los atributos positivos y cruces (rojo, #FF0000) para los atributos negativos. Utiliza un tamaño de fuente de 24pt para los puntos de comparación. La composición general debe ser equilibrada y limpia, con amplio espacio en blanco. El ambiente debe ser informativo, confiable y moderno. Incluye un borde negro delgado alrededor de toda la imagen. Asegúrate de que el diseño sea claro y fácil de entender, guiando la vista del espectador de izquierda a derecha. Agrega un sutil efecto de sombra debajo de las imágenes del producto para darles profundidad.`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["comparison", "split-screen", "modern", "clean", "informative", "pastel", "balanced"],
    totalTemplates: 27,
  },
  {
    id: "before-after",
    name: "Before & After",
    nameEs: "Antes y Después",
    description: "Split-screen showing transformation with before/after states, percentage badges and ratings.",
    descriptionEs: "Pantalla dividida mostrando transformación con estados antes/después, insignias de porcentaje.",
    thumbnails: ["/presets/05_Before_After/005_Access_99.png", "/presets/05_Before_After/010_Access_203.png", "/presets/05_Before_After/014_template.png", "/presets/05_Before_After/001_template.png"],
    masterPrompt: `Social Media Ad Template: Before & After Transformation. Create a split-screen layout with a clear division between the 'before' and 'after' states. Use a clean, pastel color palette with a light background (e.g., #f0f0f0) and accent colors in a complementary shade (e.g., #4285f4). Typography should be clean and modern, using a sans-serif font like Open Sans or Montserrat. Use a bold font weight for the headline (e.g., 36pt) and a regular font weight for the body text (e.g., 16pt). Headline text should be placed at the top, centered, in mixed case. 'Before' and 'After' labels should be placed above their respective images in a smaller font size (e.g., 14pt) and a slightly muted color. Include product photos in both the 'before' and 'after' sections, showcasing the transformation. Add a subtle arrow or line to visually connect the two states. Incorporate a percentage badge or star rating to highlight the positive results. Use whitespace generously to create a clean and uncluttered look. The overall mood should be trustworthy, informative, and modern. Aspect ratio should be 1:1 or 4:5.`,
    masterPromptEs: `Plantilla de anuncio para redes sociales: Transformación de antes y después. Crea un diseño de pantalla dividida con una clara división entre los estados de 'antes' y 'después'. Utiliza una paleta de colores pastel limpia, con un fondo claro (por ejemplo, #f0f0f0) y colores de acento en un tono complementario (por ejemplo, #4285f4). La tipografía debe ser limpia y moderna, utilizando una fuente sans-serif como Open Sans o Montserrat. Utiliza un peso de fuente en negrita para el titular (por ejemplo, 36pt) y un peso de fuente normal para el texto del cuerpo (por ejemplo, 16pt). El texto del titular debe colocarse en la parte superior, centrado, en mayúsculas y minúsculas. Las etiquetas de 'Antes' y 'Después' deben colocarse encima de sus respectivas imágenes en un tamaño de fuente más pequeño (por ejemplo, 14pt) y un color ligeramente apagado. Incluye fotos del producto tanto en las secciones de 'antes' como de 'después', mostrando la transformación. Añade una flecha o línea sutil para conectar visualmente los dos estados. Incorpora una insignia de porcentaje o una calificación de estrellas para resaltar los resultados positivos. Utiliza el espacio en blanco generosamente para crear un aspecto limpio y ordenado. El ambiente general debe ser confiable, informativo y moderno. La relación de aspecto debe ser 1:1 o 4:5.`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["before-after", "comparison", "transformation", "clean", "modern", "informative", "split-screen"],
    totalTemplates: 18,
  },
  {
    id: "collage",
    name: "Collage",
    nameEs: "Collage",
    description: "Multi-panel layout with 3-4 sections showing product angles, lifestyle imagery, and text blocks.",
    descriptionEs: "Diseño multi-panel con 3-4 secciones mostrando ángulos del producto, estilo de vida y texto.",
    thumbnails: ["/presets/06_Collage/009_Access_255-256.png", "/presets/06_Collage/018_Access_338-339.png", "/presets/06_Collage/026_template.png", "/presets/06_Collage/001_template.png"],
    masterPrompt: `Social Media Ad Template: Collage Style. Create a multi-panel collage layout with 3-4 distinct sections. Use a bright, complementary color scheme, such as teal and coral, or a pastel palette of lavender, mint green, and peach. Typography should be clean and modern, using a sans-serif font like Montserrat or Open Sans. Headlines should be bold and prominent, using mixed case. Body copy should be concise and legible, using a lighter font weight. Include product photos from multiple angles, lifestyle imagery of people using the product, and callout labels highlighting key features. Incorporate icons to represent specific attributes, and use badges to indicate discounts or promotions. The composition should create a clear visual hierarchy, with the most important element placed in a prominent position. Use whitespace strategically to create breathing room. Alignment can be either a strict grid or a more asymmetrical arrangement. The overall mood should be modern, approachable, and informative. Add subtle shadows to text and images to create depth. Use a 1:1 aspect ratio. Ensure all elements are balanced and visually appealing. Add a call to action button with rounded corners in a contrasting color.`,
    masterPromptEs: `Plantilla de anuncio para redes sociales: Estilo Collage. Crea un diseño de collage de paneles múltiples con 3-4 secciones distintas. Utiliza una combinación de colores brillantes y complementarios, como verde azulado y coral, o una paleta pastel de lavanda, verde menta y melocotón. La tipografía debe ser limpia y moderna, utilizando una fuente sans-serif como Montserrat o Open Sans. Los titulares deben ser audaces y prominentes, utilizando mayúsculas y minúsculas combinadas. El cuerpo del texto debe ser conciso y legible, utilizando un peso de fuente más ligero. Incluye fotos de productos desde múltiples ángulos, imágenes de estilo de vida de personas que usan el producto y etiquetas de llamada que destaquen las características clave. Incorpora iconos para representar atributos específicos y utiliza insignias para indicar descuentos o promociones. La composición debe crear una jerarquía visual clara, con el elemento más importante colocado en una posición destacada. Utiliza el espacio en blanco estratégicamente para crear espacio para respirar. La alineación puede ser una cuadrícula estricta o una disposición más asimétrica. El ambiente general debe ser moderno, accesible e informativo. Agrega sombras sutiles al texto y las imágenes para crear profundidad. Utiliza una relación de aspecto de 1:1. Asegúrate de que todos los elementos estén equilibrados y sean visualmente atractivos. Agrega un botón de llamada a la acción con esquinas redondeadas en un color contrastante.`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["collage", "modern", "clean", "informative", "product-focused", "dynamic", "balanced"],
    totalTemplates: 34,
  },
  {
    id: "deals-discounts",
    name: "Deals & Discounts",
    nameEs: "Ofertas y Descuentos",
    description: "Bold promotional layout with percentage badges, bright colors, and urgency-driven CTAs.",
    descriptionEs: "Diseño promocional audaz con insignias de porcentaje, colores brillantes y CTAs de urgencia.",
    thumbnails: ["/presets/07_Deals_Discounts/014_Access_136.png", "/presets/07_Deals_Discounts/027_Access_199.png", "/presets/07_Deals_Discounts/040_Access_390-391.png", "/presets/07_Deals_Discounts/001_template.png"],
    masterPrompt: `Social Media Ad Template: Deals & Discounts Style. Create a visually striking social media ad template for promoting deals and discounts. The layout should feature a product-centered hero image, with the product prominently displayed in the center or slightly off-center. The color palette should consist of bright, attention-grabbing colors such as sky blue (#87CEEB), lime green (#32CD32), and hot pink (#FF69B4), contrasted with white (#FFFFFF) or black (#000000) text for readability. Use a bold, modern sans-serif font like Montserrat or Open Sans for headlines and body text. Headlines should be in uppercase or title case and in a heavier weight (bold or extra-bold) to draw attention. Include visual elements such as percentage badges, callout labels, arrows or lines, and icons (e.g., hearts, speech bubbles, star ratings). Place a prominent percentage badge in the upper corner to highlight the discount. Add a call-to-action button at the bottom of the image, using a contrasting color to make it stand out. The composition should be balanced and visually appealing, with a clear focal point and a logical flow of information. Use whitespace effectively to create a sense of clarity and prevent the image from feeling cluttered. The overall mood should be energetic and exciting, with a focus on value and savings. Aim to create a sense of urgency and encourage viewers to take advantage of the deals and discounts being offered.`,
    masterPromptEs: `Plantilla de anuncio para redes sociales: Estilo de ofertas y descuentos. Crea una plantilla de anuncio para redes sociales visualmente impactante para promocionar ofertas y descuentos. El diseño debe presentar una imagen de héroe centrada en el producto, con el producto mostrado de manera prominente en el centro o ligeramente descentrado. La paleta de colores debe consistir en colores brillantes y llamativos como el azul cielo (#87CEEB), el verde lima (#32CD32) y el rosa fuerte (#FF69B4), contrastados con texto blanco (#FFFFFF) o negro (#000000) para facilitar la lectura. Utilice una fuente sans-serif moderna y audaz como Montserrat o Open Sans para los titulares y el cuerpo del texto. Los titulares deben estar en mayúsculas o en mayúsculas y minúsculas y en un peso más pesado (negrita o extra-negrita) para llamar la atención. Incluya elementos visuales como insignias de porcentaje, etiquetas de llamada, flechas o líneas e iconos (por ejemplo, corazones, burbujas de diálogo, clasificaciones de estrellas). Coloque una insignia de porcentaje prominente en la esquina superior para resaltar el descuento. Agregue un botón de llamada a la acción en la parte inferior de la imagen, utilizando un color contrastante para que se destaque. La composición debe ser equilibrada y visualmente atractiva, con un punto focal claro y un flujo lógico de información. Utilice el espacio en blanco de manera efectiva para crear una sensación de claridad y evitar que la imagen se sienta abarrotada. El estado de ánimo general debe ser enérgico y emocionante, con un enfoque en el valor y los ahorros. Trate de crear una sensación de urgencia y anime a los espectadores a aprovechar las ofertas y descuentos que se ofrecen.`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["deals", "discounts", "sale", "promotional", "modern", "bold", "colorful"],
    totalTemplates: 53,
  },
  {
    id: "testimonial",
    name: "Testimonial",
    nameEs: "Testimonio",
    description: "Quote card with customer testimonial, profile photo, star ratings, and product image.",
    descriptionEs: "Tarjeta de cita con testimonio del cliente, foto de perfil, calificaciones y imagen del producto.",
    thumbnails: ["/presets/08_Testimonial/013_Access_147.png", "/presets/08_Testimonial/025_Access_257-258.png", "/presets/08_Testimonial/037_Access_394-395.png", "/presets/08_Testimonial/001_template.png"],
    masterPrompt: `Social Media Ad Template: Testimonial Style. Create a social media ad template featuring a customer testimonial. The layout should be a split-screen design, with a product image on one side and a quote card on the other. Use a soft, pastel color palette with a cream background and blush pink accents. The product image should be well-lit and professionally styled. The quote card should feature a large, bold sans-serif headline with the testimonial text below in a smaller, lighter weight sans-serif font. Include a five-star rating above the headline. The customer's name and profile photo (circular) should be placed below the testimonial text. Add subtle quote marks around the testimonial. Include a call-to-action button at the bottom of the quote card with rounded corners and a contrasting color (e.g., teal). Use a clean and modern typography style with mixed-case text. Ensure there is ample whitespace to create a clean and uncluttered look. The overall mood should be trustworthy, approachable, and positive. Aspect ratio should be 1:1 or 4:5. Add a subtle drop shadow to the quote card for depth. Use a geometric sans-serif font like Montserrat or Lato. Keep the design minimal and focus on readability and visual appeal.`,
    masterPromptEs: `Plantilla de anuncio para redes sociales: Estilo de testimonio. Crea una plantilla de anuncio para redes sociales que presente un testimonio de un cliente. El diseño debe ser de pantalla dividida, con una imagen del producto en un lado y una tarjeta de cita en el otro. Utiliza una paleta de colores pastel suaves con un fondo crema y detalles en rosa rubor. La imagen del producto debe estar bien iluminada y con un estilo profesional. La tarjeta de cita debe presentar un titular grande y en negrita con una fuente sans-serif, con el texto del testimonio debajo en una fuente sans-serif más pequeña y de peso más ligero. Incluye una calificación de cinco estrellas encima del titular. El nombre del cliente y la foto de perfil (circular) deben colocarse debajo del texto del testimonio. Agrega comillas sutiles alrededor del testimonio. Incluye un botón de llamada a la acción en la parte inferior de la tarjeta de cita con esquinas redondeadas y un color contrastante (por ejemplo, verde azulado). Utiliza un estilo de tipografía limpio y moderno con texto en mayúsculas y minúsculas. Asegúrate de que haya suficiente espacio en blanco para crear una apariencia limpia y ordenada. El ambiente general debe ser confiable, accesible y positivo. La relación de aspecto debe ser 1:1 o 4:5. Agrega una sombra sutil a la tarjeta de cita para darle profundidad. Utiliza una fuente sans-serif geométrica como Montserrat o Lato. Mantén el diseño minimalista y concéntrate en la legibilidad y el atractivo visual.`,
    suggestedAspectRatios: ["1:1", "4:5", "9:16"],
    tags: ["testimonial", "clean", "modern", "trustworthy", "minimal", "pastel", "approachable"],
    totalTemplates: 49,
  },
];

export interface ProductSubStyle {
  id: string;
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  icon: string;
}

export const PRODUCT_SUB_STYLES: ProductSubStyle[] = [
  {
    id: 'studio-hero',
    name: 'Studio Hero',
    nameEs: 'Estudio Hero',
    description: 'Clean background, pro lighting, floating shadow',
    descriptionEs: 'Fondo limpio, iluminación profesional, sombra flotante',
    icon: '✦',
  },
  {
    id: 'lifestyle',
    name: 'Lifestyle Context',
    nameEs: 'Contexto Lifestyle',
    description: 'Product in real-life scene',
    descriptionEs: 'Producto en escena real de uso',
    icon: '☀',
  },
  {
    id: 'background-swap',
    name: 'Background Swap',
    nameEs: 'Cambiar Fondo',
    description: 'Pick or describe a new background',
    descriptionEs: 'Elige o describe un fondo nuevo',
    icon: '⬡',
  },
  {
    id: 'pure-enhance',
    name: 'Pure Enhancement',
    nameEs: 'Solo Mejorar',
    description: 'Same composition, better quality',
    descriptionEs: 'Misma composición, mejor calidad',
    icon: '◈',
  },
  {
    id: 'splash-action',
    name: 'Splash / Action',
    nameEs: 'Splash / Acción',
    description: 'Dynamic elements: water, powder, light',
    descriptionEs: 'Elementos dinámicos: agua, polvo, luz',
    icon: '✧',
  },
  {
    id: 'podium',
    name: 'Podium Display',
    nameEs: 'Podio / Display',
    description: '3D pedestal with catalog lighting',
    descriptionEs: 'Pedestal 3D con iluminación de catálogo',
    icon: '▲',
  },
];

// =============================================
// LOGO GENERATOR — Archetype metadata (frontend picker)
// =============================================

export interface LogoArchetypeOption {
  id: 'auto' | 'wordmark' | 'lettermark' | 'pictorial' | 'abstract' | 'emblem';
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  icon: string;
}

export const LOGO_ARCHETYPES: LogoArchetypeOption[] = [
  {
    id: 'auto',
    name: 'Let AI Choose',
    nameEs: 'Que la IA Elija',
    description: 'AI picks the best archetype for your business',
    descriptionEs: 'La IA elige el mejor arquetipo para tu negocio',
    icon: '✨',
  },
  {
    id: 'wordmark',
    name: 'Wordmark',
    nameEs: 'Wordmark (Tipográfico)',
    description: 'Pure typography — like Google, Coca-Cola, FedEx',
    descriptionEs: 'Pura tipografía — como Google, Coca-Cola, FedEx',
    icon: 'Aa',
  },
  {
    id: 'lettermark',
    name: 'Lettermark',
    nameEs: 'Lettermark (Monograma)',
    description: 'Initials or monogram — like IBM, HBO, CNN',
    descriptionEs: 'Iniciales o monograma — como IBM, HBO, CNN',
    icon: 'M',
  },
  {
    id: 'pictorial',
    name: 'Pictorial',
    nameEs: 'Pictórico (Ícono)',
    description: 'Iconic symbol + name — like Apple, Twitter, Target',
    descriptionEs: 'Símbolo icónico + nombre — como Apple, Twitter, Target',
    icon: '◉',
  },
  {
    id: 'abstract',
    name: 'Abstract',
    nameEs: 'Abstracto',
    description: 'Geometric mark — like Nike, Pepsi, Chase',
    descriptionEs: 'Marca geométrica — como Nike, Pepsi, Chase',
    icon: '◈',
  },
  {
    id: 'emblem',
    name: 'Emblem',
    nameEs: 'Emblema (Badge)',
    description: 'Text in container — like Starbucks, Harley-Davidson',
    descriptionEs: 'Texto en contenedor — como Starbucks, Harley-Davidson',
    icon: '⬡',
  },
];

export interface LogoBackgroundOption {
  id: 'transparent' | 'white' | 'dark';
  name: string;
  nameEs: string;
}

export const LOGO_BACKGROUNDS: LogoBackgroundOption[] = [
  { id: 'transparent', name: 'Neutral', nameEs: 'Neutral' },
  { id: 'white', name: 'White', nameEs: 'Blanco' },
  { id: 'dark', name: 'Dark', nameEs: 'Oscuro' },
];

export interface LogoEnhanceTierOption {
  id: 'refine' | 'modernize' | 'rebuild';
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
}

export const LOGO_ENHANCE_TIERS: LogoEnhanceTierOption[] = [
  {
    id: 'refine',
    name: 'Refine',
    nameEs: 'Refinar',
    description: 'Minimal changes — fix execution issues',
    descriptionEs: 'Cambios mínimos — arregla la ejecución',
  },
  {
    id: 'modernize',
    name: 'Modernize',
    nameEs: 'Modernizar',
    description: 'Update to current design language',
    descriptionEs: 'Actualizar al lenguaje de diseño actual',
  },
  {
    id: 'rebuild',
    name: 'Rebuild',
    nameEs: 'Reconstruir',
    description: 'Same DNA, brand-new execution',
    descriptionEs: 'Mismo DNA, nueva ejecución',
  },
];

export default IMAGE_PRESETS;
